// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: composable/xcvm/v1beta1/intent.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransferIntent struct {
	SourceAddress      string                                  `protobuf:"bytes,1,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress string                                  `protobuf:"bytes,2,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	ClientId           string                                  `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Amount             cosmossdk_io_math.Uint                  `protobuf:"bytes,4,opt,name=amount,proto3,customtype=cosmossdk.io/math.Uint" json:"amount"`
	Bounty             github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=bounty,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"bounty"`
}

func (m *TransferIntent) Reset()         { *m = TransferIntent{} }
func (m *TransferIntent) String() string { return proto.CompactTextString(m) }
func (*TransferIntent) ProtoMessage()    {}
func (*TransferIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5047e26d000a53a3, []int{0}
}
func (m *TransferIntent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferIntent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferIntent.Merge(m, src)
}
func (m *TransferIntent) XXX_Size() int {
	return m.Size()
}
func (m *TransferIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferIntent.DiscardUnknown(m)
}

var xxx_messageInfo_TransferIntent proto.InternalMessageInfo

func (m *TransferIntent) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *TransferIntent) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *TransferIntent) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*TransferIntent)(nil), "composable.xcvm.v1beta1.TransferIntent")
}

func init() {
	proto.RegisterFile("composable/xcvm/v1beta1/intent.proto", fileDescriptor_5047e26d000a53a3)
}

var fileDescriptor_5047e26d000a53a3 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4d, 0x4f, 0x32, 0x31,
	0x10, 0xc7, 0x77, 0x79, 0x1e, 0x89, 0x34, 0xca, 0x61, 0x35, 0xba, 0x62, 0x52, 0x8c, 0xf1, 0xed,
	0x62, 0x1b, 0x62, 0xe2, 0x5d, 0x3c, 0x18, 0xae, 0x44, 0x2f, 0x5e, 0x48, 0x77, 0x5b, 0xa1, 0x81,
	0xed, 0x90, 0xed, 0x40, 0xe0, 0x0b, 0x78, 0xf6, 0x63, 0x71, 0xe4, 0x68, 0x3c, 0x10, 0x03, 0x5f,
	0xc4, 0x6c, 0xbb, 0xbe, 0x9c, 0x3a, 0xfd, 0xcf, 0xef, 0x97, 0xa6, 0x33, 0xe4, 0x2c, 0x85, 0x6c,
	0x0c, 0x56, 0x24, 0x23, 0xc5, 0x67, 0xe9, 0x34, 0xe3, 0xd3, 0x56, 0xa2, 0x50, 0xb4, 0xb8, 0x36,
	0xa8, 0x0c, 0xb2, 0x71, 0x0e, 0x08, 0xd1, 0xe1, 0x2f, 0xc5, 0x0a, 0x8a, 0x95, 0x54, 0xe3, 0x28,
	0x05, 0x9b, 0x81, 0xed, 0x39, 0x8c, 0xfb, 0x8b, 0x77, 0x1a, 0xfb, 0x7d, 0xe8, 0x83, 0xcf, 0x8b,
	0xca, 0xa7, 0xa7, 0xaf, 0x15, 0x52, 0x7f, 0xcc, 0x85, 0xb1, 0x2f, 0x2a, 0xef, 0xb8, 0x27, 0xa2,
	0x73, 0x52, 0xb7, 0x30, 0xc9, 0x53, 0xd5, 0x13, 0x52, 0xe6, 0xca, 0xda, 0x38, 0x3c, 0x09, 0xaf,
	0x6a, 0xdd, 0x5d, 0x9f, 0xde, 0xf9, 0x30, 0xe2, 0x64, 0x4f, 0x2a, 0x8b, 0xda, 0x08, 0xd4, 0x60,
	0x7e, 0xd8, 0x8a, 0x63, 0xa3, 0x3f, 0xad, 0x6f, 0xe1, 0x98, 0xd4, 0xd2, 0x91, 0x56, 0x06, 0x7b,
	0x5a, 0xc6, 0xff, 0x1c, 0xb6, 0xed, 0x83, 0x8e, 0x8c, 0x6e, 0x49, 0x55, 0x64, 0x30, 0x31, 0x18,
	0xff, 0x2f, 0x3a, 0x6d, 0xba, 0x58, 0x35, 0x83, 0x8f, 0x55, 0xf3, 0xc0, 0xff, 0xc1, 0xca, 0x21,
	0xd3, 0xc0, 0x33, 0x81, 0x03, 0xf6, 0xa4, 0x0d, 0x76, 0x4b, 0x3a, 0x7a, 0x20, 0xd5, 0xa4, 0x28,
	0xe6, 0xf1, 0x96, 0xf3, 0x78, 0xe9, 0x5d, 0xf6, 0x35, 0x0e, 0x26, 0x09, 0x4b, 0x21, 0x2b, 0xc7,
	0x50, 0x1e, 0xd7, 0x56, 0x0e, 0x39, 0xce, 0xc7, 0xca, 0xb2, 0x7b, 0xd0, 0xa6, 0x5b, 0xea, 0xed,
	0x8b, 0xc5, 0x9a, 0x86, 0xcb, 0x35, 0x0d, 0x3f, 0xd7, 0x34, 0x7c, 0xdb, 0xd0, 0x60, 0xb9, 0xa1,
	0xc1, 0xfb, 0x86, 0x06, 0xcf, 0x3b, 0x33, 0xbf, 0x09, 0x27, 0x25, 0x55, 0x37, 0xb7, 0x9b, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xb1, 0x7d, 0x82, 0xa9, 0x01, 0x00, 0x00,
}

func (m *TransferIntent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferIntent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransferIntent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Bounty.Size()
		i -= size
		if _, err := m.Bounty.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIntent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIntent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintIntent(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DestinationAddress) > 0 {
		i -= len(m.DestinationAddress)
		copy(dAtA[i:], m.DestinationAddress)
		i = encodeVarintIntent(dAtA, i, uint64(len(m.DestinationAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourceAddress) > 0 {
		i -= len(m.SourceAddress)
		copy(dAtA[i:], m.SourceAddress)
		i = encodeVarintIntent(dAtA, i, uint64(len(m.SourceAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIntent(dAtA []byte, offset int, v uint64) int {
	offset -= sovIntent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TransferIntent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceAddress)
	if l > 0 {
		n += 1 + l + sovIntent(uint64(l))
	}
	l = len(m.DestinationAddress)
	if l > 0 {
		n += 1 + l + sovIntent(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovIntent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovIntent(uint64(l))
	l = m.Bounty.Size()
	n += 1 + l + sovIntent(uint64(l))
	return n
}

func sovIntent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIntent(x uint64) (n int) {
	return sovIntent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TransferIntent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIntent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferIntent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferIntent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bounty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bounty.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIntent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIntent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIntent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIntent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIntent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIntent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIntent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIntent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIntent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIntent = fmt.Errorf("proto: unexpected end of group")
)
