// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: composable/xcvm/v1beta1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSendTransferIntent represents a message to send a transfer intent.
type MsgSendTransferIntent struct {
	// The origin composable address of the transfer intent.
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// The destination EVM chain address for the transfer intent.
	DestinationAddress string `protobuf:"bytes,2,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// The IBC light client ID for the EVM chain to execute the transfer intent on.
	ClientId string `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	// The amount of tokens to transfer.
	// TODO: The coin denom (or alternatively cosmos-sdk/types.Coin) will be added to support non-native tokens in a future commit
	Amount cosmossdk_io_math.Uint `protobuf:"bytes,4,opt,name=amount,proto3,customtype=cosmossdk.io/math.Uint" json:"amount"`
}

func (m *MsgSendTransferIntent) Reset()         { *m = MsgSendTransferIntent{} }
func (m *MsgSendTransferIntent) String() string { return proto.CompactTextString(m) }
func (*MsgSendTransferIntent) ProtoMessage()    {}
func (*MsgSendTransferIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0c0bfb695dacb5, []int{0}
}
func (m *MsgSendTransferIntent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendTransferIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendTransferIntent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendTransferIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendTransferIntent.Merge(m, src)
}
func (m *MsgSendTransferIntent) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendTransferIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendTransferIntent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendTransferIntent proto.InternalMessageInfo

func (m *MsgSendTransferIntent) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgSendTransferIntent) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *MsgSendTransferIntent) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

// MsgSendTransferIntentResponse is the response type for the Msg/SendTransferIntent RPC method.
type MsgSendTransferIntentResponse struct {
}

func (m *MsgSendTransferIntentResponse) Reset()         { *m = MsgSendTransferIntentResponse{} }
func (m *MsgSendTransferIntentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendTransferIntentResponse) ProtoMessage()    {}
func (*MsgSendTransferIntentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0c0bfb695dacb5, []int{1}
}
func (m *MsgSendTransferIntentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendTransferIntentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendTransferIntentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendTransferIntentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendTransferIntentResponse.Merge(m, src)
}
func (m *MsgSendTransferIntentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendTransferIntentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendTransferIntentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendTransferIntentResponse proto.InternalMessageInfo

// MsgVerifyTransferIntentProof represents a message to send a proof to verify
// the successful execution of a transfer intent.
type MsgVerifyTransferIntentProof struct {
	// The signer address of the transfer intent proof to verify.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// Unique id of the intent to verify the proof for
	IntentId uint64 `protobuf:"varint,2,opt,name=intentId,proto3" json:"intentId,omitempty"`
	// the transaction receipt containing the transfer intent execution.
	TxReceipt []byte `protobuf:"bytes,3,opt,name=txReceipt,proto3" json:"txReceipt,omitempty"`
	// the signature of the receipt hash containing the transfer intent execution.
	ReceiptSignature []byte `protobuf:"bytes,4,opt,name=receiptSignature,proto3" json:"receiptSignature,omitempty"`
	// the block header of the block containing the transfer intent execution.
	BlockHeader []byte `protobuf:"bytes,5,opt,name=blockHeader,proto3" json:"blockHeader,omitempty"`
	// the proof of the receipt in the block.
	ReceiptProof []byte `protobuf:"bytes,6,opt,name=receiptProof,proto3" json:"receiptProof,omitempty"`
	// the body of the beacon block containing the transfer intent execution.
	BeaconBlockBody []byte `protobuf:"bytes,7,opt,name=beaconBlockBody,proto3" json:"beaconBlockBody,omitempty"`
}

func (m *MsgVerifyTransferIntentProof) Reset()         { *m = MsgVerifyTransferIntentProof{} }
func (m *MsgVerifyTransferIntentProof) String() string { return proto.CompactTextString(m) }
func (*MsgVerifyTransferIntentProof) ProtoMessage()    {}
func (*MsgVerifyTransferIntentProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0c0bfb695dacb5, []int{2}
}
func (m *MsgVerifyTransferIntentProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVerifyTransferIntentProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVerifyTransferIntentProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVerifyTransferIntentProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVerifyTransferIntentProof.Merge(m, src)
}
func (m *MsgVerifyTransferIntentProof) XXX_Size() int {
	return m.Size()
}
func (m *MsgVerifyTransferIntentProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVerifyTransferIntentProof.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVerifyTransferIntentProof proto.InternalMessageInfo

func (m *MsgVerifyTransferIntentProof) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgVerifyTransferIntentProof) GetIntentId() uint64 {
	if m != nil {
		return m.IntentId
	}
	return 0
}

func (m *MsgVerifyTransferIntentProof) GetTxReceipt() []byte {
	if m != nil {
		return m.TxReceipt
	}
	return nil
}

func (m *MsgVerifyTransferIntentProof) GetReceiptSignature() []byte {
	if m != nil {
		return m.ReceiptSignature
	}
	return nil
}

func (m *MsgVerifyTransferIntentProof) GetBlockHeader() []byte {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

func (m *MsgVerifyTransferIntentProof) GetReceiptProof() []byte {
	if m != nil {
		return m.ReceiptProof
	}
	return nil
}

func (m *MsgVerifyTransferIntentProof) GetBeaconBlockBody() []byte {
	if m != nil {
		return m.BeaconBlockBody
	}
	return nil
}

// MsgVerifyTransferIntentProofResponse is the response type for the Msg/MsgVerifyTransferIntentProof RPC method.
type MsgVerifyTransferIntentProofResponse struct {
}

func (m *MsgVerifyTransferIntentProofResponse) Reset()         { *m = MsgVerifyTransferIntentProofResponse{} }
func (m *MsgVerifyTransferIntentProofResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVerifyTransferIntentProofResponse) ProtoMessage()    {}
func (*MsgVerifyTransferIntentProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0c0bfb695dacb5, []int{3}
}
func (m *MsgVerifyTransferIntentProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVerifyTransferIntentProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVerifyTransferIntentProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVerifyTransferIntentProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVerifyTransferIntentProofResponse.Merge(m, src)
}
func (m *MsgVerifyTransferIntentProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVerifyTransferIntentProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVerifyTransferIntentProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVerifyTransferIntentProofResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSendTransferIntent)(nil), "composable.xcvm.v1beta1.MsgSendTransferIntent")
	proto.RegisterType((*MsgSendTransferIntentResponse)(nil), "composable.xcvm.v1beta1.MsgSendTransferIntentResponse")
	proto.RegisterType((*MsgVerifyTransferIntentProof)(nil), "composable.xcvm.v1beta1.MsgVerifyTransferIntentProof")
	proto.RegisterType((*MsgVerifyTransferIntentProofResponse)(nil), "composable.xcvm.v1beta1.MsgVerifyTransferIntentProofResponse")
}

func init() { proto.RegisterFile("composable/xcvm/v1beta1/tx.proto", fileDescriptor_6d0c0bfb695dacb5) }

var fileDescriptor_6d0c0bfb695dacb5 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0x6e, 0x2b, 0xcc, 0x8d, 0x04, 0x33, 0xb0, 0x65, 0xd1, 0x48, 0x4b, 0x34, 0x4d,
	0x53, 0x0f, 0x89, 0x0a, 0x62, 0x87, 0x49, 0x1c, 0xe8, 0x89, 0x1e, 0x2a, 0xa1, 0x0c, 0x38, 0x70,
	0x99, 0x9c, 0xc4, 0x0d, 0xd6, 0x1a, 0x3b, 0xb2, 0xbd, 0xaa, 0x95, 0x38, 0x20, 0x3e, 0x01, 0x1c,
	0xb9, 0xf0, 0x19, 0xf6, 0x31, 0x76, 0x9c, 0x38, 0x21, 0x0e, 0x13, 0x6a, 0x0f, 0xfb, 0x1a, 0x28,
	0x76, 0xda, 0xad, 0xd0, 0x56, 0x62, 0x97, 0xd6, 0xef, 0xff, 0x7e, 0xcf, 0x79, 0x7f, 0x3f, 0x1b,
	0xd4, 0x23, 0x96, 0x66, 0x4c, 0xa0, 0xb0, 0x87, 0xfd, 0x41, 0xd4, 0x4f, 0xfd, 0x7e, 0x33, 0xc4,
	0x12, 0x35, 0x7d, 0x39, 0xf0, 0x32, 0xce, 0x24, 0x83, 0x5b, 0xd7, 0x84, 0x97, 0x13, 0x5e, 0x41,
	0xd8, 0x1b, 0x28, 0x25, 0x94, 0xf9, 0xea, 0x57, 0xb3, 0xf6, 0xee, 0xa2, 0xdd, 0x08, 0x95, 0x98,
	0xca, 0x82, 0xda, 0x8a, 0x98, 0x48, 0x99, 0xf0, 0x53, 0x91, 0xf8, 0xfd, 0x66, 0xfe, 0x57, 0x24,
	0xb6, 0x75, 0xe2, 0x58, 0x45, 0xbe, 0x0e, 0x8a, 0xd4, 0xc3, 0x84, 0x25, 0x4c, 0xeb, 0xf9, 0x4a,
	0xab, 0xee, 0x0f, 0x03, 0x3c, 0xea, 0x88, 0xe4, 0x08, 0xd3, 0xf8, 0x0d, 0x47, 0x54, 0x74, 0x31,
	0x6f, 0xab, 0x2f, 0xc1, 0x27, 0xc0, 0xec, 0x72, 0x96, 0x1e, 0xa3, 0x38, 0xe6, 0x58, 0x08, 0xcb,
	0xa8, 0x1b, 0xfb, 0xeb, 0x41, 0x35, 0xd7, 0x5e, 0x6a, 0x09, 0xfa, 0xe0, 0x41, 0x8c, 0x85, 0x24,
	0x14, 0x49, 0xc2, 0xe8, 0x94, 0x2c, 0x2b, 0x12, 0xde, 0x48, 0x4d, 0x0a, 0x6c, 0x70, 0x37, 0xea,
	0x11, 0x4c, 0x65, 0x3b, 0xb6, 0x56, 0x14, 0x35, 0x8d, 0xe1, 0x01, 0xa8, 0xa0, 0x94, 0x9d, 0x52,
	0x69, 0xad, 0xe6, 0x99, 0x96, 0x73, 0x7e, 0x59, 0x2b, 0xfd, 0xba, 0xac, 0x6d, 0x6a, 0x17, 0x22,
	0x3e, 0xf1, 0x08, 0xf3, 0x53, 0x24, 0x3f, 0x78, 0x6f, 0x09, 0x95, 0x41, 0x41, 0x1f, 0x6e, 0x7c,
	0xbe, 0x3a, 0x6b, 0xcc, 0xb4, 0xea, 0xd6, 0xc0, 0xe3, 0xb9, 0x9e, 0x02, 0x2c, 0x32, 0x46, 0x05,
	0x76, 0xbf, 0x95, 0xc1, 0x4e, 0x47, 0x24, 0xef, 0x30, 0x27, 0xdd, 0xe1, 0x2c, 0xf3, 0x9a, 0x33,
	0xd6, 0x85, 0x9b, 0xa0, 0x22, 0x48, 0x42, 0x31, 0x2f, 0x6c, 0x17, 0x51, 0x6e, 0x40, 0x0f, 0xa2,
	0x1d, 0x2b, 0x9b, 0xab, 0xc1, 0x34, 0x86, 0x3b, 0x60, 0x5d, 0x0e, 0x02, 0x1c, 0x61, 0x92, 0x49,
	0xe5, 0xce, 0x0c, 0xae, 0x05, 0xd8, 0x00, 0xf7, 0xb9, 0x5e, 0x1e, 0x91, 0x84, 0x22, 0x79, 0xca,
	0xb1, 0x32, 0x6a, 0x06, 0xff, 0xe8, 0xb0, 0x0e, 0xaa, 0x61, 0x8f, 0x45, 0x27, 0xaf, 0x30, 0x8a,
	0x31, 0xb7, 0xd6, 0x14, 0x76, 0x53, 0x82, 0x2e, 0x30, 0x8b, 0x2a, 0xd5, 0xaf, 0x55, 0x51, 0xc8,
	0x8c, 0x06, 0xf7, 0xc1, 0xbd, 0x10, 0xa3, 0x88, 0xd1, 0x56, 0x5e, 0xd8, 0x62, 0xf1, 0xd0, 0xba,
	0xa3, 0xb0, 0xbf, 0xe5, 0xc3, 0x6a, 0x7e, 0x84, 0x85, 0x45, 0x77, 0x0f, 0xec, 0x2e, 0x3b, 0x9a,
	0xc9, 0x19, 0x3e, 0xfd, 0x5e, 0x06, 0x2b, 0x1d, 0x91, 0xc0, 0x8f, 0x00, 0xce, 0xb9, 0x3d, 0x9e,
	0xb7, 0xe0, 0xd2, 0x7b, 0x73, 0x27, 0x63, 0x1f, 0xfc, 0x1f, 0x3f, 0xe9, 0x02, 0x7e, 0x35, 0xc0,
	0xf6, 0xe2, 0x31, 0x3e, 0x5f, 0xb6, 0xeb, 0xc2, 0x32, 0xfb, 0xc5, 0xad, 0xca, 0x26, 0x3d, 0xd9,
	0x6b, 0x9f, 0xae, 0xce, 0x1a, 0x46, 0x6b, 0xef, 0x7c, 0xe4, 0x18, 0x17, 0x23, 0xc7, 0xf8, 0x3d,
	0x72, 0x8c, 0x2f, 0x63, 0xa7, 0x74, 0x31, 0x76, 0x4a, 0x3f, 0xc7, 0x4e, 0xe9, 0xbd, 0x39, 0xd0,
	0x6f, 0x5b, 0x0e, 0x33, 0x2c, 0xc2, 0x8a, 0x7a, 0x89, 0xcf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xec, 0x56, 0xfe, 0x26, 0x49, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendTransferIntent(ctx context.Context, in *MsgSendTransferIntent, opts ...grpc.CallOption) (*MsgSendTransferIntentResponse, error)
	VerifyTransferIntentProof(ctx context.Context, in *MsgVerifyTransferIntentProof, opts ...grpc.CallOption) (*MsgVerifyTransferIntentProofResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendTransferIntent(ctx context.Context, in *MsgSendTransferIntent, opts ...grpc.CallOption) (*MsgSendTransferIntentResponse, error) {
	out := new(MsgSendTransferIntentResponse)
	err := c.cc.Invoke(ctx, "/composable.xcvm.v1beta1.Msg/SendTransferIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VerifyTransferIntentProof(ctx context.Context, in *MsgVerifyTransferIntentProof, opts ...grpc.CallOption) (*MsgVerifyTransferIntentProofResponse, error) {
	out := new(MsgVerifyTransferIntentProofResponse)
	err := c.cc.Invoke(ctx, "/composable.xcvm.v1beta1.Msg/VerifyTransferIntentProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendTransferIntent(context.Context, *MsgSendTransferIntent) (*MsgSendTransferIntentResponse, error)
	VerifyTransferIntentProof(context.Context, *MsgVerifyTransferIntentProof) (*MsgVerifyTransferIntentProofResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendTransferIntent(ctx context.Context, req *MsgSendTransferIntent) (*MsgSendTransferIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransferIntent not implemented")
}
func (*UnimplementedMsgServer) VerifyTransferIntentProof(ctx context.Context, req *MsgVerifyTransferIntentProof) (*MsgVerifyTransferIntentProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTransferIntentProof not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendTransferIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendTransferIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendTransferIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.xcvm.v1beta1.Msg/SendTransferIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendTransferIntent(ctx, req.(*MsgSendTransferIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VerifyTransferIntentProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVerifyTransferIntentProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VerifyTransferIntentProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/composable.xcvm.v1beta1.Msg/VerifyTransferIntentProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VerifyTransferIntentProof(ctx, req.(*MsgVerifyTransferIntentProof))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "composable.xcvm.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransferIntent",
			Handler:    _Msg_SendTransferIntent_Handler,
		},
		{
			MethodName: "VerifyTransferIntentProof",
			Handler:    _Msg_VerifyTransferIntentProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "composable/xcvm/v1beta1/tx.proto",
}

func (m *MsgSendTransferIntent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendTransferIntent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendTransferIntent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DestinationAddress) > 0 {
		i -= len(m.DestinationAddress)
		copy(dAtA[i:], m.DestinationAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DestinationAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendTransferIntentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendTransferIntentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendTransferIntentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgVerifyTransferIntentProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVerifyTransferIntentProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVerifyTransferIntentProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BeaconBlockBody) > 0 {
		i -= len(m.BeaconBlockBody)
		copy(dAtA[i:], m.BeaconBlockBody)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BeaconBlockBody)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ReceiptProof) > 0 {
		i -= len(m.ReceiptProof)
		copy(dAtA[i:], m.ReceiptProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReceiptProof)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BlockHeader) > 0 {
		i -= len(m.BlockHeader)
		copy(dAtA[i:], m.BlockHeader)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BlockHeader)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReceiptSignature) > 0 {
		i -= len(m.ReceiptSignature)
		copy(dAtA[i:], m.ReceiptSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReceiptSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TxReceipt) > 0 {
		i -= len(m.TxReceipt)
		copy(dAtA[i:], m.TxReceipt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxReceipt)))
		i--
		dAtA[i] = 0x1a
	}
	if m.IntentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.IntentId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVerifyTransferIntentProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVerifyTransferIntentProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVerifyTransferIntentProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSendTransferIntent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DestinationAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSendTransferIntentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgVerifyTransferIntentProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.IntentId != 0 {
		n += 1 + sovTx(uint64(m.IntentId))
	}
	l = len(m.TxReceipt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ReceiptSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BlockHeader)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ReceiptProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BeaconBlockBody)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgVerifyTransferIntentProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSendTransferIntent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendTransferIntent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendTransferIntent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendTransferIntentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendTransferIntentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendTransferIntentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVerifyTransferIntentProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVerifyTransferIntentProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVerifyTransferIntentProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntentId", wireType)
			}
			m.IntentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IntentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxReceipt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxReceipt = append(m.TxReceipt[:0], dAtA[iNdEx:postIndex]...)
			if m.TxReceipt == nil {
				m.TxReceipt = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiptSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiptSignature = append(m.ReceiptSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.ReceiptSignature == nil {
				m.ReceiptSignature = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeader", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHeader = append(m.BlockHeader[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHeader == nil {
				m.BlockHeader = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiptProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiptProof = append(m.ReceiptProof[:0], dAtA[iNdEx:postIndex]...)
			if m.ReceiptProof == nil {
				m.ReceiptProof = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconBlockBody", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeaconBlockBody = append(m.BeaconBlockBody[:0], dAtA[iNdEx:postIndex]...)
			if m.BeaconBlockBody == nil {
				m.BeaconBlockBody = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVerifyTransferIntentProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVerifyTransferIntentProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVerifyTransferIntentProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
